config/routes.rb
Rails.application.routes.draw do
  root 'tracks#index'
  
  resources :tracks
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :tracksegment
  attr_accessible :description, :elevation, :latitude, :longitude, :name, :point_created_at
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :tracksegments, :dependent => :destroy
  has_many :points, :through => :tracksegments
  has_attached_file :gpx
  accepts_nested_attributes_for :tracksegments
  before_save :parse_file

  def parse_file
    tempfile = gpx.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_tracks(node)
    end
  end

  def parse_tracks(node)
    if node.node_name.eql? 'trk'
      node.elements.each do |node|
        parse_track_segments(node)
      end
    end
  end

  def parse_track_segments(node)
    if node.node_name.eql? 'trkseg'
      tmp_segment = Tracksegment.new
      node.elements.each do |node|
        parse_points(node,tmp_segment)
      end
      self.tracksegments << tmp_segment
    end
  end

  def parse_points(node,tmp_segment)
    if node.node_name.eql? 'trkpt'
      tmp_point = Point.new
      tmp_point.latitude = node.attr("lat")
      tmp_point.longitude = node.attr("lon")
      node.elements.each do |node|
        tmp_point.name = node.text.to_s if node.name.eql? 'name'
        tmp_point.elevation = node.text.to_s if node.name.eql? 'ele'
        tmp_point.description = node.text.to_s if node.name.eql? 'desc'
        tmp_point.point_created_at = node.text.to_s if node.name.eql? 'time'
      end
      tmp_segment.points << tmp_point
    end
  end
end

app/models/tracksegment.rb
class Tracksegment < ActiveRecord::Base
  belongs_to :track
  has_many :points, :dependent => :destroy
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tracks_params
    params.require(:track).permit(:name, :gpx)
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperclipNokigiri</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/tracks/_form.html.erb
<%= form_for @track, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gpx, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :gpx %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tracks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/index.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:gpx_file_name) %></th>
      <th><%= model_class.human_attribute_name(:gpx_content_type) %></th>
      <th><%= model_class.human_attribute_name(:gpx_file_size) %></th>
      <th><%= model_class.human_attribute_name(:gpx_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= link_to track.id, track_path(track) %></td>
        <td><%= track.name %></td>
        <td><%= track.gpx_file_name %></td>
        <td><%= track.gpx_content_type %></td>
        <td><%= track.gpx_file_size %></td>
        <td><%= track.gpx_updated_at %></td>
        <td><%=l track.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_track_path(track), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      track_path(track),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_track_path,
            :class => 'btn btn-primary' %>

app/views/tracks/new.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/show.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @track.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_name) %>:</strong></dt>
  <dd><%= @track.gpx_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_content_type) %>:</strong></dt>
  <dd><%= @track.gpx_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_size) %>:</strong></dt>
  <dd><%= @track.gpx_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_updated_at) %>:</strong></dt>
  <dd><%= @track.gpx_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tracks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_track_path(@track), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              track_path(@track),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Point No.</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Elevation</th>
    <th>Description</th>
    <th>Time</th>
  </tr>
  </thead>
  <tbody>
  <% @track.points.each do |point| %>
    <tr>
      <td><%= point.id %></td>
      <td><%= point.name %></td>
      <td><%= point.latitude %></td>
      <td><%= point.longitude %></td>
      <td><%= point.elevation %></td>
      <td><%= point.description %></td>
      <td><%= point.point_created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tracks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_track_path(@track), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              track_path(@track),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>